import type { Prisma } from "../../generated/prisma/client";
import {
    BodyShape,
    ClothingItemType,
    ClothingSlot,
    FavoriteStyle,
    FormalityLevel,
    Gender,
    ItemFit,
    NoveltyLevel,
    Occasion,
    Season,
    SilhouetteTag,
} from "../../generated/prisma/client";

const F = FavoriteStyle;
const O = Occasion;
const S = Season;
const B = BodyShape;
const Sil = SilhouetteTag;

const dailyUni = [O.DAILY, O.UNIVERSITY, O.TRAVEL] as Occasion[];
const workDaily = [O.DAILY, O.WORK, O.UNIVERSITY] as Occasion[];
const smartOccasions = [O.WORK, O.DATE_CAFE, O.FRIENDS_GATHERING, O.PARTY] as Occasion[];
const formalOccasions = [O.FORMAL_EVENT, O.WORK, O.PARTY] as Occasion[];
const socialOccasions = [O.FRIENDS_GATHERING, O.DATE_CAFE, O.PARTY, O.DAILY] as Occasion[];
const allYear = [S.ALL_SEASON] as Season[];
const warmSeasons = [S.SPRING, S.SUMMER, S.ALL_SEASON] as Season[];
const coolSeasons = [S.FALL, S.WINTER, S.ALL_SEASON] as Season[];
const midSeasons = [S.SPRING, S.FALL, S.ALL_SEASON] as Season[];

const mostMaleShapes = [
    B.MALE_TRAPEZOID,
    B.MALE_RECTANGLE,
    B.MALE_TRIANGLE,
    B.MALE_OVAL,
    B.MALE_INVERTED_TRIANGLE,
] as BodyShape[];

export const menClothingItems: Prisma.ClothingItemCreateInput[] = [
    // —— Tops ——
    {
        slug: "m-tshirt-basic",
        nameEn: "Basic Crew T-Shirt",
        nameFa: "تی‌شرت ساده یقه گرد",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TSHIRT,
        styles: [F.CASUAL_AND_DAILY, F.SPORT, F.MINIMAL],
        occasions: dailyUni,
        seasons: warmSeasons,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.FITTED_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-tshirt-oversized",
        nameEn: "Oversized T-Shirt",
        nameFa: "تی‌شرت اورسایز",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TSHIRT,
        styles: [F.STREET, F.CASUAL_AND_DAILY],
        occasions: dailyUni,
        seasons: warmSeasons,
        fit: ItemFit.LOOSE,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: [B.MALE_OVAL, B.MALE_RECTANGLE, B.MALE_TRIANGLE],
        silhouetteTags: [Sil.LOOSE_TOP, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.MIXED,
    },
    {
        slug: "m-tshirt-long-sleeve",
        nameEn: "Long-Sleeve T-Shirt",
        nameFa: "تی‌شرت آستین بلند",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TSHIRT,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL],
        occasions: dailyUni,
        seasons: coolSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-polo-classic",
        nameEn: "Classic Polo Shirt",
        nameFa: "پولوشرت کلاسیک",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.POLO,
        styles: [F.MALE_SMART_AND_CASUAL, F.CASUAL_AND_DAILY, F.CLASSIC],
        occasions: [...workDaily, O.DATE_CAFE],
        seasons: warmSeasons,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.BALANCED,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_RECTANGLE, B.MALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.FITTED_TOP],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-polo-slim",
        nameEn: "Slim Polo Shirt",
        nameFa: "پولوشرت اسلیم",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.POLO,
        styles: [F.MALE_SMART_AND_CASUAL, F.MINIMAL],
        occasions: smartOccasions,
        seasons: warmSeasons,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_INVERTED_TRIANGLE, B.MALE_RECTANGLE],
        silhouetteTags: [Sil.FITTED_TOP],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-shirt-oxford",
        nameEn: "Oxford Dress Shirt",
        nameFa: "پیراهن مردانه آکسفورد",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.SHIRT,
        styles: [F.CLASSIC, F.MALE_SMART_AND_CASUAL, F.FORMAL],
        occasions: [O.WORK, O.FORMAL_EVENT, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_RECTANGLE, B.MALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.STRUCTURED_SHOULDER, Sil.FITTED_TOP],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-shirt-casual",
        nameEn: "Casual Button Shirt",
        nameFa: "پیراهن کژوال مردانه",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.SHIRT,
        styles: [F.CASUAL_AND_DAILY, F.MALE_SMART_AND_CASUAL],
        occasions: [...dailyUni, O.DATE_CAFE],
        seasons: warmSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-shirt-linen",
        nameEn: "Linen Summer Shirt",
        nameFa: "پیراهن لینن تابستانی",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.SHIRT,
        styles: [F.MINIMAL, F.CASUAL_AND_DAILY, F.MALE_ROMANTIC_AND_DIFFERENT],
        occasions: [O.TRAVEL, O.DATE_CAFE, O.DAILY],
        seasons: [S.SPRING, S.SUMMER],
        fit: ItemFit.LOOSE,
        coverage: null,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LOOSE_TOP, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-shirt-formal-slim",
        nameEn: "Slim Formal Shirt",
        nameFa: "پیراهن رسمی اسلیم",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.SHIRT,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: formalOccasions,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_INVERTED_TRIANGLE, B.MALE_RECTANGLE],
        silhouetteTags: [Sil.FITTED_TOP, Sil.STRUCTURED_SHOULDER],
        novelty: NoveltyLevel.FAMILIAR,
    },

    // —— Knit / hoodie / sweatshirt ——
    {
        slug: "m-hoodie-classic",
        nameEn: "Classic Hoodie",
        nameFa: "هودی کلاسیک",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.HOODIE,
        styles: [F.SPORT, F.STREET, F.CASUAL_AND_DAILY],
        occasions: dailyUni,
        seasons: coolSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-hoodie-zip",
        nameEn: "Zip Hoodie",
        nameFa: "هودی زیپ‌دار",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.HOODIE,
        styles: [F.SPORT, F.CASUAL_AND_DAILY],
        occasions: dailyUni,
        seasons: coolSeasons,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LAYERABLE, Sil.SOFT_SHOULDER],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-sweatshirt-crew",
        nameEn: "Crew Sweatshirt",
        nameFa: "سویشرت ساده",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.SWEATSHIRT,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL, F.SPORT],
        occasions: dailyUni,
        seasons: coolSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-knit-crew",
        nameEn: "Crew Knit Sweater",
        nameFa: "ژاکت بافت یقه گرد",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.KNIT,
        styles: [F.CLASSIC, F.MALE_SMART_AND_CASUAL, F.MINIMAL],
        occasions: [...workDaily, O.DATE_CAFE],
        seasons: coolSeasons,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_RECTANGLE, B.MALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.FITTED_TOP, Sil.SOFT_SHOULDER, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-knit-vneck",
        nameEn: "V-Neck Knit",
        nameFa: "ژاکت بافت یقه هفت",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.KNIT,
        styles: [F.CLASSIC, F.FORMAL],
        occasions: [O.WORK, O.FORMAL_EVENT, O.DATE_CAFE],
        seasons: coolSeasons,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.FITTED_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-sweater-chunky",
        nameEn: "Chunky Sweater",
        nameFa: "سویشرت بافت ضخیم",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.SWEATER,
        styles: [F.CASUAL_AND_DAILY, F.MALE_ROMANTIC_AND_DIFFERENT],
        occasions: socialOccasions,
        seasons: [S.FALL, S.WINTER],
        fit: ItemFit.LOOSE,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: [B.MALE_OVAL, B.MALE_RECTANGLE, B.MALE_TRIANGLE],
        silhouetteTags: [Sil.LOOSE_TOP, Sil.SOFT_SHOULDER],
        novelty: NoveltyLevel.MIXED,
    },

    // —— Jackets / blazers / overshirts ——
    {
        slug: "m-blazer-classic",
        nameEn: "Classic Blazer",
        nameFa: "کت بلیزر کلاسیک",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.BLAZER,
        styles: [F.FORMAL, F.CLASSIC, F.MALE_SMART_AND_CASUAL],
        occasions: formalOccasions,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_INVERTED_TRIANGLE, B.MALE_RECTANGLE],
        silhouetteTags: [Sil.STRUCTURED_SHOULDER, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-blazer-unstructured",
        nameEn: "Unstructured Blazer",
        nameFa: "بلیزر نرم غیرساخت‌دار",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.BLAZER,
        styles: [F.MALE_SMART_AND_CASUAL, F.MINIMAL],
        occasions: smartOccasions,
        seasons: midSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.SOFT_SHOULDER, Sil.LAYERABLE],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-denim-jacket",
        nameEn: "Denim Jacket",
        nameFa: "کت جین",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.DENIM_JACKET,
        styles: [F.CASUAL_AND_DAILY, F.STREET],
        occasions: dailyUni,
        seasons: midSeasons,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LAYERABLE, Sil.STRUCTURED_SHOULDER],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-overshirt-utility",
        nameEn: "Utility Overshirt",
        nameFa: "اورشرت کاربردی",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.OVERSHIRT,
        styles: [F.STREET, F.CASUAL_AND_DAILY, F.MALE_ROMANTIC_AND_DIFFERENT],
        occasions: [...dailyUni, O.FRIENDS_GATHERING],
        seasons: midSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LAYERABLE, Sil.LOOSE_TOP],
        novelty: NoveltyLevel.MIXED,
    },
    {
        slug: "m-overshirt-flannel",
        nameEn: "Flannel Overshirt",
        nameFa: "اورشرت فلانل",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.OVERSHIRT,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL],
        occasions: dailyUni,
        seasons: coolSeasons,
        fit: ItemFit.LOOSE,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: [B.MALE_OVAL, B.MALE_RECTANGLE, B.MALE_TRIANGLE],
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-blazer-party",
        nameEn: "Evening Blazer",
        nameFa: "بلیزر شب / مهمانی",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.BLAZER,
        styles: [F.FORMAL, F.MALE_ROMANTIC_AND_DIFFERENT],
        occasions: [O.PARTY, O.FORMAL_EVENT, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.STRUCTURED_SHOULDER, Sil.FITTED_TOP],
        novelty: NoveltyLevel.CREATIVE,
    },

    // —— Bottoms ——
    {
        slug: "m-jeans-straight",
        nameEn: "Straight Jeans",
        nameFa: "شلوار جین راسته",
        gender: Gender.MALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.JEANS,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL, F.STREET],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.STRAIGHT_LEG, Sil.SLIM_BOTTOM],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-jeans-slim",
        nameEn: "Slim Jeans",
        nameFa: "شلوار جین اسلیم",
        gender: Gender.MALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.JEANS,
        styles: [F.CASUAL_AND_DAILY, F.STREET],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_RECTANGLE, B.MALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.SLIM_BOTTOM, Sil.TAPERED],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-jeans-relaxed",
        nameEn: "Relaxed Jeans",
        nameFa: "شلوار جین آزاد",
        gender: Gender.MALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.JEANS,
        styles: [F.CASUAL_AND_DAILY, F.SPORT],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.LOOSE,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: [B.MALE_OVAL, B.MALE_TRIANGLE, B.MALE_RECTANGLE],
        silhouetteTags: [Sil.WIDE_LEG, Sil.VOLUME_BOTTOM, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-trousers-chinos",
        nameEn: "Chino Trousers",
        nameFa: "شلوار کتان / چینو",
        gender: Gender.MALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.TROUSERS,
        styles: [F.MALE_SMART_AND_CASUAL, F.CLASSIC, F.CASUAL_AND_DAILY],
        occasions: workDaily,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.STRAIGHT_LEG, Sil.TAPERED],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-trousers-tailored",
        nameEn: "Tailored Trousers",
        nameFa: "شلوار پارچه‌ای رسمی",
        gender: Gender.MALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.TROUSERS,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: formalOccasions,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.MALE_TRAPEZOID, B.MALE_RECTANGLE, B.MALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.SLIM_BOTTOM, Sil.TAPERED],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-trousers-wide",
        nameEn: "Wide Trousers",
        nameFa: "شلوار پارچه‌ای گشاد",
        gender: Gender.MALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.TROUSERS,
        styles: [F.MINIMAL, F.MALE_ROMANTIC_AND_DIFFERENT],
        occasions: smartOccasions,
        seasons: midSeasons,
        fit: ItemFit.LOOSE,
        coverage: null,
        formality: FormalityLevel.BALANCED,
        bodyShapes: [B.MALE_OVAL, B.MALE_TRIANGLE, B.MALE_RECTANGLE],
        silhouetteTags: [Sil.WIDE_LEG, Sil.VOLUME_BOTTOM],
        novelty: NoveltyLevel.CREATIVE,
    },
    {
        slug: "m-cargo-pants",
        nameEn: "Cargo Pants",
        nameFa: "شلوار کارگو",
        gender: Gender.MALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.CARGO_PANTS,
        styles: [F.STREET, F.SPORT, F.CASUAL_AND_DAILY],
        occasions: [O.DAILY, O.UNIVERSITY, O.TRAVEL, O.FRIENDS_GATHERING],
        seasons: allYear,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.STRAIGHT_LEG, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.MIXED,
    },
    {
        slug: "m-trousers-travel",
        nameEn: "Travel Stretch Trousers",
        nameFa: "شلوار راحت سفر",
        gender: Gender.MALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.TROUSERS,
        styles: [F.CASUAL_AND_DAILY, F.SPORT],
        occasions: [O.TRAVEL, O.DAILY, O.UNIVERSITY],
        seasons: allYear,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.STRAIGHT_LEG, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.FAMILIAR,
    },

    // —— Shoes ——
    {
        slug: "m-sneakers-classic",
        nameEn: "Classic Sneakers",
        nameFa: "کفش کتانی کلاسیک",
        gender: Gender.MALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.SNEAKERS,
        styles: [F.CASUAL_AND_DAILY, F.SPORT, F.STREET],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-sneakers-minimal",
        nameEn: "Minimal Clean Sneakers",
        nameFa: "کتانی مینیمال",
        gender: Gender.MALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.SNEAKERS,
        styles: [F.MINIMAL, F.CASUAL_AND_DAILY, F.MALE_SMART_AND_CASUAL],
        occasions: [...dailyUni, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-sneakers-chunky",
        nameEn: "Chunky Sneakers",
        nameFa: "کتانی حجیم",
        gender: Gender.MALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.SNEAKERS,
        styles: [F.STREET, F.SPORT],
        occasions: [O.DAILY, O.UNIVERSITY, O.FRIENDS_GATHERING],
        seasons: allYear,
        fit: ItemFit.LOOSE,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.BOLD,
    },
    {
        slug: "m-loafers-classic",
        nameEn: "Classic Loafers",
        nameFa: "کفش لوفر کلاسیک",
        gender: Gender.MALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.LOAFERS,
        styles: [F.MALE_SMART_AND_CASUAL, F.CLASSIC, F.MINIMAL],
        occasions: [O.WORK, O.DATE_CAFE, O.PARTY],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-loafers-suede",
        nameEn: "Suede Loafers",
        nameFa: "لوفر جیر",
        gender: Gender.MALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.LOAFERS,
        styles: [F.MALE_ROMANTIC_AND_DIFFERENT, F.MALE_SMART_AND_CASUAL],
        occasions: smartOccasions,
        seasons: midSeasons,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-formal-oxford",
        nameEn: "Oxford Formal Shoes",
        nameFa: "کفش رسمی آکسفورد",
        gender: Gender.MALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.FORMAL_SHOES,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: formalOccasions,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-formal-derby",
        nameEn: "Derby Formal Shoes",
        nameFa: "کفش رسمی دربی",
        gender: Gender.MALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.FORMAL_SHOES,
        styles: [F.FORMAL, F.CLASSIC, F.MALE_SMART_AND_CASUAL],
        occasions: [O.WORK, O.FORMAL_EVENT, O.PARTY],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },

    // —— Accessories ——
    {
        slug: "m-watch-classic",
        nameEn: "Classic Watch",
        nameFa: "ساعت کلاسیک",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.WATCH,
        styles: [F.CLASSIC, F.MALE_SMART_AND_CASUAL, F.MINIMAL],
        occasions: [...workDaily, O.FORMAL_EVENT, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-watch-sport",
        nameEn: "Sport Watch",
        nameFa: "ساعت اسپرت",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.WATCH,
        styles: [F.SPORT, F.CASUAL_AND_DAILY],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-belt-leather",
        nameEn: "Leather Belt",
        nameFa: "کمربند چرمی",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.BELT,
        styles: [F.CLASSIC, F.FORMAL, F.MALE_SMART_AND_CASUAL],
        occasions: [...workDaily, O.FORMAL_EVENT],
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-belt-casual",
        nameEn: "Casual Belt",
        nameFa: "کمربند کژوال",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.BELT,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-glasses-classic",
        nameEn: "Classic Glasses",
        nameFa: "عینک کلاسیک",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.GLASSES,
        styles: [F.MINIMAL, F.CLASSIC, F.CASUAL_AND_DAILY],
        occasions: workDaily,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-glasses-bold",
        nameEn: "Bold Frame Glasses",
        nameFa: "عینک فریم درشت",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.GLASSES,
        styles: [F.STREET, F.MALE_ROMANTIC_AND_DIFFERENT],
        occasions: socialOccasions,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.CREATIVE,
    },
    {
        slug: "m-hat-cap",
        nameEn: "Casual Cap",
        nameFa: "کلاه کپ",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.HAT,
        styles: [F.SPORT, F.STREET, F.CASUAL_AND_DAILY],
        occasions: dailyUni,
        seasons: warmSeasons,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-bag-crossbody",
        nameEn: "Crossbody Bag",
        nameFa: "کیف دوشی مردانه",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.BAG,
        styles: [F.CASUAL_AND_DAILY, F.STREET, F.MINIMAL],
        occasions: [...dailyUni, O.TRAVEL],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.MIXED,
    },
    {
        slug: "m-tie-classic",
        nameEn: "Classic Tie",
        nameFa: "کراوات کلاسیک",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.TIE_OR_BOW,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: [O.FORMAL_EVENT, O.WORK],
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-bow-tie",
        nameEn: "Bow Tie",
        nameFa: "پاپیون",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.TIE_OR_BOW,
        styles: [F.FORMAL, F.MALE_ROMANTIC_AND_DIFFERENT],
        occasions: [O.FORMAL_EVENT, O.PARTY],
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.BOLD,
    },
    {
        slug: "m-jewelry-bracelet",
        nameEn: "Simple Bracelet",
        nameFa: "دستبند ساده",
        gender: Gender.MALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.JEWELRY,
        styles: [F.MALE_ROMANTIC_AND_DIFFERENT, F.STREET, F.MINIMAL],
        occasions: socialOccasions,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.CREATIVE,
    },

    // —— Extra work / travel fillers ——
    {
        slug: "m-shirt-work-daily",
        nameEn: "Daily Work Shirt",
        nameFa: "پیراهن اداری روزمره",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.SHIRT,
        styles: [F.MALE_SMART_AND_CASUAL, F.CLASSIC],
        occasions: [O.WORK, O.DAILY, O.UNIVERSITY],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.FITTED_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-tshirt-pocket",
        nameEn: "Pocket T-Shirt",
        nameFa: "تی‌شرت جیب‌دار",
        gender: Gender.MALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TSHIRT,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL],
        occasions: dailyUni,
        seasons: warmSeasons,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.FITTED_TOP],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "m-overshirt-travel",
        nameEn: "Travel Overshirt",
        nameFa: "اورشرت سفر",
        gender: Gender.MALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.OVERSHIRT,
        styles: [F.CASUAL_AND_DAILY, F.SPORT],
        occasions: [O.TRAVEL, O.DAILY, O.UNIVERSITY],
        seasons: midSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [Sil.LAYERABLE, Sil.LOOSE_TOP],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "m-sneakers-travel",
        nameEn: "Comfort Travel Sneakers",
        nameFa: "کتانی راحت سفر",
        gender: Gender.MALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.SNEAKERS,
        styles: [F.SPORT, F.CASUAL_AND_DAILY],
        occasions: [O.TRAVEL, O.DAILY, O.UNIVERSITY],
        seasons: allYear,
        fit: ItemFit.SEMI_LOOSE,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostMaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
];
