import type { Prisma } from "../../generated/prisma/client";
import {
    BodyShape,
    ClothingItemType,
    ClothingSlot,
    CoverageLevel,
    FavoriteStyle,
    FormalityLevel,
    Gender,
    ItemFit,
    NoveltyLevel,
    Occasion,
    Season,
    SilhouetteTag,
} from "../../generated/prisma/client";

const F = FavoriteStyle;
const O = Occasion;
const S = Season;
const B = BodyShape;
const Sil = SilhouetteTag;

const dailyUni = [O.DAILY, O.UNIVERSITY, O.TRAVEL] as Occasion[];
const workDaily = [O.DAILY, O.WORK, O.UNIVERSITY] as Occasion[];
const smartOccasions = [O.WORK, O.DATE_CAFE, O.FRIENDS_GATHERING, O.PARTY] as Occasion[];
const formalOccasions = [O.FORMAL_EVENT, O.WORK, O.PARTY] as Occasion[];
const socialOccasions = [O.FRIENDS_GATHERING, O.DATE_CAFE, O.PARTY, O.DAILY] as Occasion[];
const allYear = [S.ALL_SEASON] as Season[];
const warmSeasons = [S.SPRING, S.SUMMER, S.ALL_SEASON] as Season[];
const coolSeasons = [S.FALL, S.WINTER, S.ALL_SEASON] as Season[];
const midSeasons = [S.SPRING, S.FALL, S.ALL_SEASON] as Season[];

const mostFemaleShapes = [
    B.FEMALE_HOURGLASS,
    B.FEMALE_PEAR,
    B.FEMALE_RECTANGLE,
    B.FEMALE_APPLE,
    B.FEMALE_INVERTED_TRIANGLE,
] as BodyShape[];

export const womenClothingItems: Prisma.ClothingItemCreateInput[] = [
    // —— Mantos / long outerwear (Iran-core) ——
    {
        slug: "w-manto-classic-long",
        nameEn: "Classic Long Manto",
        nameFa: "مانتوی کلاسیک بلند",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.CLASSIC, F.CASUAL_AND_DAILY],
        occasions: workDaily,
        seasons: allYear,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.LONG_LINE, Sil.SOFT_SHOULDER, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-manto-minimal-straight",
        nameEn: "Minimal Straight Manto",
        nameFa: "مانتوی مینیمال راسته",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.MINIMAL, F.CLASSIC],
        occasions: [...workDaily, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.FEMALE_RECTANGLE, B.FEMALE_HOURGLASS, B.FEMALE_PEAR],
        silhouetteTags: [Sil.LONG_LINE, Sil.STRAIGHT_LEG, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-manto-relaxed-daily",
        nameEn: "Relaxed Daily Manto",
        nameFa: "مانتوی روزمره آزاد",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL],
        occasions: dailyUni,
        seasons: warmSeasons,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LONG_LINE, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-manto-belted-defined-waist",
        nameEn: "Belted Waist Manto",
        nameFa: "مانتوی کمردار",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.CLASSIC, F.FEMALE_ROMANTIC_AND_ELEGANT],
        occasions: smartOccasions,
        seasons: midSeasons,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.FEMALE_HOURGLASS, B.FEMALE_RECTANGLE, B.FEMALE_APPLE],
        silhouetteTags: [Sil.DEFINED_WAIST, Sil.LONG_LINE, Sil.SOFT_SHOULDER],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-manto-structured-work",
        nameEn: "Structured Work Manto",
        nameFa: "مانتوی رسمی اداری",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: [O.WORK, O.FORMAL_EVENT],
        seasons: coolSeasons,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.FEMALE_RECTANGLE, B.FEMALE_INVERTED_TRIANGLE, B.FEMALE_HOURGLASS],
        silhouetteTags: [Sil.STRUCTURED_SHOULDER, Sil.LONG_LINE, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-manto-lightweight-summer",
        nameEn: "Lightweight Summer Manto",
        nameFa: "مانتوی نخی تابستانی",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL],
        occasions: dailyUni,
        seasons: [S.SPRING, S.SUMMER],
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.LONG_LINE, Sil.LOOSE_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-manto-artistic-panel",
        nameEn: "Artistic Paneled Manto",
        nameFa: "مانتوی هنری تکه‌دوزی",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.FEMALE_ARITISTIC_AND_CREATIVE, F.STREET],
        occasions: socialOccasions,
        seasons: midSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.BALANCED,
        bodyShapes: [B.FEMALE_RECTANGLE, B.FEMALE_PEAR, B.FEMALE_HOURGLASS],
        silhouetteTags: [Sil.LONG_LINE, Sil.SOFT_SHOULDER],
        novelty: NoveltyLevel.CREATIVE,
    },
    {
        slug: "w-manto-winter-wool",
        nameEn: "Wool Winter Manto",
        nameFa: "مانتوی پشمی زمستانی",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.CLASSIC, F.CASUAL_AND_DAILY],
        occasions: [...workDaily, O.TRAVEL],
        seasons: [S.FALL, S.WINTER],
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.LONG_LINE, Sil.LAYERABLE, Sil.SOFT_SHOULDER],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-long-coat-trench",
        nameEn: "Long Trench Coat",
        nameFa: "کت بلند ترنچ",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.LONG_COAT,
        styles: [F.CLASSIC, F.MINIMAL],
        occasions: [...workDaily, O.TRAVEL],
        seasons: coolSeasons,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.FEMALE_RECTANGLE, B.FEMALE_HOURGLASS, B.FEMALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.LONG_LINE, Sil.STRUCTURED_SHOULDER, Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-long-coat-oversized",
        nameEn: "Oversized Long Coat",
        nameFa: "کت بلند اورسایز",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.LONG_COAT,
        styles: [F.STREET, F.MINIMAL],
        occasions: socialOccasions,
        seasons: coolSeasons,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: [B.FEMALE_APPLE, B.FEMALE_RECTANGLE, B.FEMALE_PEAR],
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LONG_LINE, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.MIXED,
    },

    // —— Blazers ——
    {
        slug: "w-blazer-classic",
        nameEn: "Classic Blazer",
        nameFa: "بلیزر کلاسیک",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.BLAZER,
        styles: [F.CLASSIC, F.FORMAL, F.MINIMAL],
        occasions: [O.WORK, O.FORMAL_EVENT, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.FEMALE_RECTANGLE, B.FEMALE_INVERTED_TRIANGLE, B.FEMALE_HOURGLASS],
        silhouetteTags: [Sil.STRUCTURED_SHOULDER, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-blazer-relaxed",
        nameEn: "Relaxed Blazer",
        nameFa: "بلیزر آزاد",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.BLAZER,
        styles: [F.MINIMAL, F.CASUAL_AND_DAILY],
        occasions: smartOccasions,
        seasons: midSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.BALANCED,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.SOFT_SHOULDER, Sil.LAYERABLE, Sil.LOOSE_TOP],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-blazer-cropped",
        nameEn: "Cropped Blazer",
        nameFa: "بلیزر کوتاه",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.BLAZER,
        styles: [F.FEMALE_ROMANTIC_AND_ELEGANT, F.STREET],
        occasions: socialOccasions,
        seasons: warmSeasons,
        fit: ItemFit.FITTED,
        coverage: CoverageLevel.BALANCED,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.FEMALE_HOURGLASS, B.FEMALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.CROPPED, Sil.STRUCTURED_SHOULDER, Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.CREATIVE,
    },

    // —— Tops ——
    {
        slug: "w-blouse-classic-button",
        nameEn: "Classic Button Blouse",
        nameFa: "شومیز کلاسیک دکمه‌دار",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.BLOUSE,
        styles: [F.CLASSIC, F.MINIMAL],
        occasions: workDaily,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.FITTED_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-blouse-flowy",
        nameEn: "Flowy Blouse",
        nameFa: "شومیز آزاد و نرم",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.BLOUSE,
        styles: [F.FEMALE_ROMANTIC_AND_ELEGANT, F.CASUAL_AND_DAILY],
        occasions: socialOccasions,
        seasons: warmSeasons,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.BALANCED,
        bodyShapes: [B.FEMALE_APPLE, B.FEMALE_PEAR, B.FEMALE_RECTANGLE],
        silhouetteTags: [Sil.LOOSE_TOP, Sil.SOFT_SHOULDER],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-blouse-high-neck",
        nameEn: "High-Neck Blouse",
        nameFa: "شومیز یقه ایستاده",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.BLOUSE,
        styles: [F.CLASSIC, F.MINIMAL],
        occasions: workDaily,
        seasons: coolSeasons,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.FITTED_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-shirt-crisp",
        nameEn: "Crisp Shirt",
        nameFa: "پیراهن رسمی ساده",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.SHIRT,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: [O.WORK, O.FORMAL_EVENT],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.FEMALE_RECTANGLE, B.FEMALE_HOURGLASS],
        silhouetteTags: [Sil.STRUCTURED_SHOULDER, Sil.FITTED_TOP],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-shirt-oversized",
        nameEn: "Oversized Shirt",
        nameFa: "پیراهن اورسایز",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.SHIRT,
        styles: [F.STREET, F.MINIMAL],
        occasions: dailyUni,
        seasons: warmSeasons,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.BALANCED,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: [B.FEMALE_APPLE, B.FEMALE_RECTANGLE, B.FEMALE_PEAR],
        silhouetteTags: [Sil.LOOSE_TOP, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.MIXED,
    },
    {
        slug: "w-tshirt-basic",
        nameEn: "Basic Crew T-Shirt",
        nameFa: "تی‌شرت ساده یقه گرد",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TSHIRT,
        styles: [F.CASUAL_AND_DAILY, F.SPORT, F.MINIMAL],
        occasions: dailyUni,
        seasons: warmSeasons,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.BALANCED,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.FITTED_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-tshirt-long-sleeve",
        nameEn: "Long-Sleeve T-Shirt",
        nameFa: "تی‌شرت آستین بلند",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TSHIRT,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL],
        occasions: dailyUni,
        seasons: coolSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-top-layering",
        nameEn: "Layering Top",
        nameFa: "تاپ لایه‌ای ساده",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TOP,
        styles: [F.MINIMAL, F.CASUAL_AND_DAILY],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: CoverageLevel.BALANCED,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: [B.FEMALE_HOURGLASS, B.FEMALE_RECTANGLE],
        silhouetteTags: [Sil.FITTED_TOP, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-top-knit-soft",
        nameEn: "Soft Knit Top",
        nameFa: "بلوز بافت نرم",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TOP,
        styles: [F.FEMALE_ROMANTIC_AND_ELEGANT, F.CASUAL_AND_DAILY],
        occasions: socialOccasions,
        seasons: coolSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.BALANCED,
        bodyShapes: [B.FEMALE_PEAR, B.FEMALE_HOURGLASS, B.FEMALE_APPLE],
        silhouetteTags: [Sil.SOFT_SHOULDER, Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-top-artistic-print",
        nameEn: "Artistic Print Top",
        nameFa: "تاپ چاپی هنری",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.TOP,
        styles: [F.FEMALE_ARITISTIC_AND_CREATIVE, F.STREET],
        occasions: socialOccasions,
        seasons: warmSeasons,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.BALANCED,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.FITTED_TOP],
        novelty: NoveltyLevel.BOLD,
    },

    // —— Bottoms ——
    {
        slug: "w-jeans-straight",
        nameEn: "Straight Jeans",
        nameFa: "شلوار جین راسته",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.JEANS,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL, F.STREET],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.STRAIGHT_LEG, Sil.SLIM_BOTTOM],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-jeans-wide-leg",
        nameEn: "Wide-Leg Jeans",
        nameFa: "شلوار جین بگ / گشاد",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.JEANS,
        styles: [F.STREET, F.CASUAL_AND_DAILY],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: [B.FEMALE_PEAR, B.FEMALE_APPLE, B.FEMALE_RECTANGLE],
        silhouetteTags: [Sil.WIDE_LEG, Sil.VOLUME_BOTTOM],
        novelty: NoveltyLevel.MIXED,
    },
    {
        slug: "w-jeans-slim",
        nameEn: "Slim Jeans",
        nameFa: "شلوار جین اسلیم",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.JEANS,
        styles: [F.CASUAL_AND_DAILY, F.SPORT],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: [B.FEMALE_HOURGLASS, B.FEMALE_RECTANGLE, B.FEMALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.SLIM_BOTTOM, Sil.TAPERED],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-trousers-tailored",
        nameEn: "Tailored Trousers",
        nameFa: "شلوار پارچه‌ای رسمی",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.TROUSERS,
        styles: [F.FORMAL, F.CLASSIC, F.MINIMAL],
        occasions: [O.WORK, O.FORMAL_EVENT, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.FEMALE_RECTANGLE, B.FEMALE_HOURGLASS, B.FEMALE_INVERTED_TRIANGLE],
        silhouetteTags: [Sil.STRAIGHT_LEG, Sil.SLIM_BOTTOM],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-trousers-wide",
        nameEn: "Wide Trousers",
        nameFa: "شلوار پارچه‌ای گشاد",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.TROUSERS,
        styles: [F.MINIMAL, F.FEMALE_ROMANTIC_AND_ELEGANT],
        occasions: smartOccasions,
        seasons: midSeasons,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.FEMALE_PEAR, B.FEMALE_APPLE, B.FEMALE_RECTANGLE],
        silhouetteTags: [Sil.WIDE_LEG, Sil.VOLUME_BOTTOM, Sil.A_LINE],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-trousers-tapered",
        nameEn: "Tapered Trousers",
        nameFa: "شلوار پارچه‌ای دم‌قلم",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.TROUSERS,
        styles: [F.CLASSIC, F.CASUAL_AND_DAILY],
        occasions: workDaily,
        seasons: allYear,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.TAPERED, Sil.SLIM_BOTTOM],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-skirt-midi-a-line",
        nameEn: "Midi A-Line Skirt",
        nameFa: "دامن میدی کلوش",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.SKIRT,
        styles: [F.FEMALE_ROMANTIC_AND_ELEGANT, F.CLASSIC],
        occasions: smartOccasions,
        seasons: warmSeasons,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.FEMALE_PEAR, B.FEMALE_HOURGLASS, B.FEMALE_APPLE],
        silhouetteTags: [Sil.A_LINE, Sil.VOLUME_BOTTOM, Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-skirt-long-modest",
        nameEn: "Long Modest Skirt",
        nameFa: "دامن بلند پوشیده",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.SKIRT,
        styles: [F.CLASSIC, F.MINIMAL],
        occasions: workDaily,
        seasons: allYear,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.A_LINE, Sil.LONG_LINE, Sil.VOLUME_BOTTOM],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-skirt-pencil",
        nameEn: "Pencil Skirt",
        nameFa: "دامن مدادی",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.SKIRT,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: formalOccasions,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.FEMALE_HOURGLASS, B.FEMALE_RECTANGLE],
        silhouetteTags: [Sil.SLIM_BOTTOM, Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.MIXED,
    },
    {
        slug: "w-skirt-pleated",
        nameEn: "Pleated Skirt",
        nameFa: "دامن پلیسه",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.SKIRT,
        styles: [F.FEMALE_ARITISTIC_AND_CREATIVE, F.FEMALE_ROMANTIC_AND_ELEGANT],
        occasions: socialOccasions,
        seasons: midSeasons,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.BALANCED,
        bodyShapes: [B.FEMALE_PEAR, B.FEMALE_RECTANGLE],
        silhouetteTags: [Sil.A_LINE, Sil.VOLUME_BOTTOM],
        novelty: NoveltyLevel.CREATIVE,
    },

    // —— Shoes ——
    {
        slug: "w-sneakers-classic",
        nameEn: "Classic Sneakers",
        nameFa: "کفش کتانی کلاسیک",
        gender: Gender.FEMALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.SNEAKERS,
        styles: [F.CASUAL_AND_DAILY, F.SPORT, F.STREET],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-sneakers-chunky",
        nameEn: "Chunky Sneakers",
        nameFa: "کتانی حجیم",
        gender: Gender.FEMALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.SNEAKERS,
        styles: [F.STREET, F.SPORT],
        occasions: [O.DAILY, O.UNIVERSITY, O.FRIENDS_GATHERING],
        seasons: allYear,
        fit: ItemFit.LOOSE,
        coverage: null,
        formality: FormalityLevel.VERY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.BOLD,
    },
    {
        slug: "w-heels-classic",
        nameEn: "Classic Heels",
        nameFa: "کفش پاشنه‌دار کلاسیک",
        gender: Gender.FEMALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.HEELS,
        styles: [F.FORMAL, F.FEMALE_ROMANTIC_AND_ELEGANT, F.CLASSIC],
        occasions: formalOccasions,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-heels-block",
        nameEn: "Block Heel Pumps",
        nameFa: "کفش پاشنه ضخیم",
        gender: Gender.FEMALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.HEELS,
        styles: [F.CLASSIC, F.CASUAL_AND_DAILY],
        occasions: [O.WORK, O.DATE_CAFE, O.PARTY],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-formal-flats",
        nameEn: "Formal Flats",
        nameFa: "کفش رسمی بدون پاشنه",
        gender: Gender.FEMALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.FORMAL_SHOES,
        styles: [F.CLASSIC, F.MINIMAL, F.FORMAL],
        occasions: [O.WORK, O.FORMAL_EVENT, O.DAILY],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-formal-loafers",
        nameEn: "Women's Loafers",
        nameFa: "کفش لوفر زنانه",
        gender: Gender.FEMALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.FORMAL_SHOES,
        styles: [F.MINIMAL, F.CLASSIC],
        occasions: workDaily,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },

    // —— Accessories ——
    {
        slug: "w-bag-tote-daily",
        nameEn: "Daily Tote Bag",
        nameFa: "کیف دستی روزمره",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.CASUAL_BAG,
        styles: [F.CASUAL_AND_DAILY, F.MINIMAL],
        occasions: dailyUni,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-bag-crossbody",
        nameEn: "Crossbody Bag",
        nameFa: "کیف دوشی",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.CASUAL_BAG,
        styles: [F.CASUAL_AND_DAILY, F.STREET],
        occasions: [...dailyUni, O.TRAVEL],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-bag-structured",
        nameEn: "Structured Handbag",
        nameFa: "کیف رسمی ساخت‌دار",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.BAG,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: [O.WORK, O.FORMAL_EVENT, O.PARTY],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.FORMAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-scarf-light",
        nameEn: "Light Scarf",
        nameFa: "شال یا روسری سبک",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.SCARF,
        styles: [F.CLASSIC, F.CASUAL_AND_DAILY, F.FEMALE_ROMANTIC_AND_ELEGANT],
        occasions: [...workDaily, O.FORMAL_EVENT],
        seasons: allYear,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-scarf-statement",
        nameEn: "Statement Scarf",
        nameFa: "شال خاص و رنگی",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.SCARF,
        styles: [F.FEMALE_ARITISTIC_AND_CREATIVE, F.STREET],
        occasions: socialOccasions,
        seasons: midSeasons,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.LAYERABLE],
        novelty: NoveltyLevel.CREATIVE,
    },
    {
        slug: "w-jewelry-minimal",
        nameEn: "Minimal Jewelry Set",
        nameFa: "زیورآلات مینیمال",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.JEWELRY,
        styles: [F.MINIMAL, F.CLASSIC],
        occasions: [...workDaily, ...socialOccasions],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-jewelry-bold",
        nameEn: "Bold Statement Jewelry",
        nameFa: "زیورآلات جسورانه",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.JEWELRY,
        styles: [F.FEMALE_ARITISTIC_AND_CREATIVE, F.FEMALE_ROMANTIC_AND_ELEGANT],
        occasions: [O.PARTY, O.DATE_CAFE, O.FRIENDS_GATHERING],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.BOLD,
    },
    {
        slug: "w-glasses-classic",
        nameEn: "Classic Glasses",
        nameFa: "عینک کلاسیک",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.GLASSES,
        styles: [F.MINIMAL, F.CLASSIC, F.CASUAL_AND_DAILY],
        occasions: workDaily,
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.BALANCED,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-watch-simple",
        nameEn: "Simple Watch",
        nameFa: "ساعت ساده",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.WATCH,
        styles: [F.MINIMAL, F.CLASSIC],
        occasions: [...workDaily, O.FORMAL_EVENT],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-belt-thin",
        nameEn: "Thin Belt",
        nameFa: "کمربند باریک",
        gender: Gender.FEMALE,
        slot: ClothingSlot.ACCESSORY,
        itemType: ClothingItemType.BELT,
        styles: [F.CLASSIC, F.FEMALE_ROMANTIC_AND_ELEGANT],
        occasions: smartOccasions,
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: null,
        formality: FormalityLevel.SMART_CASUAL,
        bodyShapes: [B.FEMALE_HOURGLASS, B.FEMALE_RECTANGLE, B.FEMALE_APPLE],
        silhouetteTags: [Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },

    // —— Extra seasonal / travel pieces to reach ~60 ——
    {
        slug: "w-manto-travel-lightweight",
        nameEn: "Travel Lightweight Manto",
        nameFa: "مانتوی سبک سفر",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.CASUAL_AND_DAILY, F.SPORT],
        occasions: [O.TRAVEL, O.DAILY, O.UNIVERSITY],
        seasons: warmSeasons,
        fit: ItemFit.LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.LOOSE_TOP, Sil.LONG_LINE, Sil.LAYERABLE],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-blouse-work-silk-feel",
        nameEn: "Smooth Work Blouse",
        nameFa: "شومیز اداری نرم",
        gender: Gender.FEMALE,
        slot: ClothingSlot.TOP,
        itemType: ClothingItemType.BLOUSE,
        styles: [F.FORMAL, F.CLASSIC],
        occasions: [O.WORK, O.FORMAL_EVENT, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.FITTED,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.FEMALE_HOURGLASS, B.FEMALE_RECTANGLE],
        silhouetteTags: [Sil.FITTED_TOP, Sil.DEFINED_WAIST],
        novelty: NoveltyLevel.SLIGHTLY_NEW,
    },
    {
        slug: "w-trousers-travel-stretch",
        nameEn: "Stretch Travel Trousers",
        nameFa: "شلوار پارچه‌ای راحت سفر",
        gender: Gender.FEMALE,
        slot: ClothingSlot.BOTTOM,
        itemType: ClothingItemType.TROUSERS,
        styles: [F.CASUAL_AND_DAILY, F.SPORT],
        occasions: [O.TRAVEL, O.DAILY, O.UNIVERSITY],
        seasons: allYear,
        fit: ItemFit.SEMI_LOOSE,
        coverage: CoverageLevel.COVERED_COMFORTABLE,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [Sil.STRAIGHT_LEG, Sil.RELAXED_WAIST],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-sneakers-minimal-white",
        nameEn: "Minimal Clean Sneakers",
        nameFa: "کتانی مینیمال تمیز",
        gender: Gender.FEMALE,
        slot: ClothingSlot.SHOES,
        itemType: ClothingItemType.SNEAKERS,
        styles: [F.MINIMAL, F.CASUAL_AND_DAILY],
        occasions: [...dailyUni, O.DATE_CAFE],
        seasons: allYear,
        fit: ItemFit.BALANCED,
        coverage: null,
        formality: FormalityLevel.MOSTLY_CASUAL,
        bodyShapes: mostFemaleShapes,
        silhouetteTags: [],
        novelty: NoveltyLevel.FAMILIAR,
    },
    {
        slug: "w-manto-party-elegant",
        nameEn: "Elegant Evening Manto",
        nameFa: "مانتوی شیک مهمانی",
        gender: Gender.FEMALE,
        slot: ClothingSlot.OUTERWEAR,
        itemType: ClothingItemType.MANTO,
        styles: [F.FEMALE_ROMANTIC_AND_ELEGANT, F.FORMAL],
        occasions: [O.PARTY, O.FORMAL_EVENT, O.DATE_CAFE],
        seasons: coolSeasons,
        fit: ItemFit.BALANCED,
        coverage: CoverageLevel.FULLY_COVERED,
        formality: FormalityLevel.FORMAL,
        bodyShapes: [B.FEMALE_HOURGLASS, B.FEMALE_RECTANGLE, B.FEMALE_PEAR],
        silhouetteTags: [Sil.DEFINED_WAIST, Sil.LONG_LINE, Sil.STRUCTURED_SHOULDER],
        novelty: NoveltyLevel.CREATIVE,
    },
];
